In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iriscsv/Iris.csv

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('/kaggle/input/iriscsv/Iris.csv')

In [7]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [9]:
df.drop('Id', axis=1, inplace=True)

In [10]:
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [13]:
x = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']

In [15]:
x

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [14]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

**Train Test Split**

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, shuffle=True)

In [18]:
X_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
65             6.7           3.1            4.4           1.4
147            6.5           3.0            5.2           2.0
27             5.2           3.5            1.5           0.2
92             5.8           2.6            4.0           1.2
35             5.0           3.2            1.2           0.2
..             ...           ...            ...           ...
36             5.5           3.5            1.3           0.2
72             6.3           2.5            4.9           1.5
112            6.8           3.0            5.5           2.1
110            6.5           3.2            5.1           2.0
18             5.7           3.8            1.7           0.3

[120 rows x 4 columns]

In [19]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
53             5.5           2.3            4.0           1.3
95             5.7           3.0            4.2           1.2
106            4.9           2.5            4.5           1.7
59             5.2           2.7            3.9           1.4
125            7.2           3.2            6.0           1.8
101            5.8           2.7            5.1           1.9
24             4.8           3.4            1.9           0.2
77             6.7           3.0            5.0           1.7
49             5.0           3.3            1.4           0.2
117            7.7           3.8            6.7           2.2
100            6.3           3.3            6.0           2.5
37             4.9           3.1            1.5           0.1
111            6.4           2.7            5.3           1.9
39             5.1           3.4            1.5           0.2
87             6.3           2.3            4.4           1.3
133            6.3           2.8            5.1           1.5
45             4.8           3.0            1.4           0.3
94             5.6           2.7            4.2           1.3
83             6.0           2.7            5.1           1.6
97             6.2           2.9            4.3           1.3
67             5.8           2.7            4.1           1.0
29             4.7           3.2            1.6           0.2
38             4.4           3.0            1.3           0.2
47             4.6           3.2            1.4           0.2
63             6.1           2.9            4.7           1.4
103            6.3           2.9            5.6           1.8
114            5.8           2.8            5.1           2.4
134            6.1           2.6            5.6           1.4
70             5.9           3.2            4.8           1.8
121            5.6           2.8            4.9           2.0

In [21]:
y_train

65     Iris-versicolor
147     Iris-virginica
27         Iris-setosa
92     Iris-versicolor
35         Iris-setosa
            ...
36         Iris-setosa
72     Iris-versicolor
112     Iris-virginica
110     Iris-virginica
18         Iris-setosa
Name: Species, Length: 120, dtype: object

In [22]:
y_test

53     Iris-versicolor
95     Iris-versicolor
106     Iris-virginica
59     Iris-versicolor
125     Iris-virginica
101     Iris-virginica
24         Iris-setosa
77     Iris-versicolor
49         Iris-setosa
117     Iris-virginica
100     Iris-virginica
37         Iris-setosa
111     Iris-virginica
39         Iris-setosa
87     Iris-versicolor
133     Iris-virginica
45         Iris-setosa
94     Iris-versicolor
83     Iris-versicolor
97     Iris-versicolor
67     Iris-versicolor
29         Iris-setosa
38         Iris-setosa
47         Iris-setosa
63     Iris-versicolor
103     Iris-virginica
114     Iris-virginica
134     Iris-virginica
70     Iris-versicolor
121     Iris-virginica
Name: Species, dtype: object

**Model Building, Training and Evaluation**

In [26]:
# Training the model with Logistic Regression and checking the score/accuracy
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
model.score(X_test, y_test)

/opt/conda/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9777777777777777

In [27]:
# Training the model with K Nearest Neighbour Clssification and checking the score/accuracy
from sklearn.neighbors import KNeighborsClassifier
model_KNN = KNeighborsClassifier(n_neighbors=10)
model_KNN.fit(X_train, y_train)
model_KNN.score(X_test, y_test)

0.9777777777777777

**Model Prediction**

In [28]:
model.predict([[5.1, 3.8, 1.9, 0.4]])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array(['Iris-setosa'], dtype=object)

In [30]:
df.iloc[40]

SepalLengthCm            5.0
SepalWidthCm             3.5
PetalLengthCm            1.3
PetalWidthCm             0.3
Species          Iris-setosa
Name: 40, dtype: object